name: Assert Integration & Delivery
on:
  push:
    branches: [ main ]
    paths:
      - './*gradle*'
      - .github/workflows/assert-integration-delivery.yml
      - assert/**/*.kt*
      - buildSrc/**/*.kt*
  workflow_dispatch:
permissions: read-all
jobs:
  # ---------- Stage 1 ----------
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.5
  # ---------- Stage 2 ----------
  check-and-deliver:
    name: Check and deliver to OSSRH
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: validate-wrapper
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Check the application
        run: ./gradlew assert:check
      - name: Deliver package to OSSRH
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USER: ${{ secrets.GIT_USER }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          OS: ${{ matrix.os }}
        run: ./gradlew assert:publishAllPublicationsToOSSRHRepository
