name: Continuous Integration
on:
  push:
    branches: [ master ]
    paths: [ /**/*.kts, /*gradle*, .github/workflows/*, src/** ]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test --no-daemon
