name: CSV - Delivery
on:
  push:
    branches: [ release/csv-v* ]
    paths:
      - './*gradle*'
      - .github/workflows/csv-delivery.yml
      - buildSrc/**/*.kt*
      - csv/**/*.kt*
  workflow_dispatch:
jobs:
  deliver:
    name: Deliver to OSSRH
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 8
          cache: gradle
      - name: Deliver package to OSSRH
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USER: ${{ secrets.GIT_USER }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew csv:publishAllPublicationsToOSSRHRepository --no-daemon
