name: Delivery
on:
  push:
    branches: [ master ]
    paths:
      - '*.kts'
      - '*gradle*'
      - .github/workflows/delivery.yml
      - src/**
jobs:
  deliver:
    name: Deliver to OSSRH
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deliver package to OSSRH
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USER: ${{ secrets.GIT_USER }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew publishAllPublicationToOSSRHRepository --no-daemon
