name: Deployment
on:
  release:
    types: [ released ]
  workflow_dispatch:
jobs:
  # ---------- Stage 1 ----------
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
  # ---------- Stage 2 ----------
  deploy-kmp-js-jvm-linux:
    name: Deploy Kotlin Multiplatform, JS, JVM and Linux publications to GitHub Packages
    runs-on: ubuntu-latest
    needs: validate-wrapper
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: ./gradlew publishJsJvmAndLinuxPublicationsToGitHubRepository --no-daemon
  deploy-macos:
    name: Deploy macOS publication to GitHub Packages
    runs-on: macos-latest
    needs: validate-wrapper
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: ./gradlew publishMacOSPublicationToGitHubRepository --no-daemon
  deploy-windows:
    name: Deploy Windows publication to GitHub Packages
    runs-on: windows-latest
    needs: validate-wrapper
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: ./gradlew publishWindowsPublicationToGitHubRepository --no-daemon
  deploy-docs:
    name: Deploy documentation to GitHub Pages
    runs-on: ubuntu-latest
    needs: validate-wrapper
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate documentation with Dokka
        run: ./gradlew dokkaHtml --no-daemon
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: docs
          folder: build/dokka
          git-config-email: ${{ secrets.GIT_EMAIL }}
          git-config-name: ${{ secrets.GIT_USER }}
