name: Integration
on:
  pull_request:
    branches: [ master ]
    paths:
      - '*.kts'
      - '*gradle*'
      - .github/workflows/integration.yml
      - src/**
jobs:
  # ---------- Stage 1 ----------
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
  # ---------- Stage 2 ----------
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    needs: validate-wrapper
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test --no-daemon
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    needs: validate-wrapper
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test --no-daemon
