name: Integration
on:
  push:
    branches: [ main, release/* ]
    paths:
      - '*.kts'
      - '*gradle*'
      - .github/workflows/delivery.yml
      - .github/workflows/integration.yml
      - src/**
  workflow_dispatch:
jobs:
  # ---------- Stage 1 ----------
  print_context:
    name: Print event context
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo $EVENT_CONTEXT
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
  # ---------- Stage 2 ----------
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    needs: validate-wrapper
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test --no-daemon
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    needs: validate-wrapper
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test --no-daemon
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    needs: validate-wrapper
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test --no-daemon
