name: Integration
on:
  push:
    branches: [ main ]
    paths:
      - '*.kts'
      - '*gradle*'
      - .github/workflows/delivery.yml
      - .github/workflows/integration.yml
      - src/**
jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run tests
        run: ./gradlew test --no-daemon
