name: Integration & Delivery
on:
  push:
    branches: [ main, release/* ]
    paths:
      - '*.kts'
      - '*gradle*'
      - .github/workflows/integration-delivery.yml
      - src/**
  workflow_dispatch:
permissions: read-all
jobs:
  # ---------- Stage 1 ----------
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
  # ---------- Stage 2 ----------
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    needs: validate-wrapper
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test --no-daemon
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    needs: validate-wrapper
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    needs: validate-wrapper
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test --no-daemon
  # ---------- Stage 3 ----------
  deliver:
    name: Deliver to OSSRH
    runs-on: ubuntu-latest
    needs: [ test-macos, test-ubuntu, test-windows ]
    if: github.event.ref != 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deliver package to OSSRH
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USER: ${{ secrets.GIT_USER }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: ./gradlew publishAllPublicationToOSSRHRepository
