name: Integration
on:
  pull_request:
    branches: [ main ]
    paths:
      - '**gradle*'
      - '**.java'
      - '**.kt*'
      - '!.github/workflows/gradle-wrapper-upgrade.yml'
      - .github/workflows/integration.yml
      - gradle/libs.versions.toml
      - gradle/wrapper/
      - src/api/types.api
      - yarn.lock
  push:
    branches: [ main ]
    paths:
      - '**gradle*'
      - '**.java'
      - '**.kt*'
      - '!.github/workflows/gradle-wrapper-upgrade.yml'
      - .github/workflows/integration.yml
      - gradle/libs.versions.toml
      - gradle/wrapper/
      - src/api/types.api
      - yarn.lock
  workflow_dispatch:
env:
  JAVA_DISTRIBUTION: temurin
  JAVA_VERSION: 17
jobs:
  # --------------------------------- Stage 1 ----------------------------------
  gradle-checks:
    name: Gradle checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.2
      - name: Check Gradle plugins
        run: ./gradlew :plugins:check --no-daemon
  # --------------------------------- Stage 2 ----------------------------------
  js-test:
    name: Kotlin/JS tests
    needs: gradle-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Test 'internal' subproject
        run: ./gradlew :types-internal:jsTest
      - name: Test root project
        run: ./gradlew :jsTest
  jvm-checks:
    name: Kotlin/JVM checks
    needs: gradle-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Test 'internal' subproject
        run: ./gradlew :types-internal:jvmTest
      - name: Test 'java-compatibility' subproject
        run: ./gradlew :java-compatibility:test
      - name: Check root project
        run: ./gradlew :jvmTest :jvmApiCheck
  linux-test:
    name: Kotlin Native tests for Linux
    needs: gradle-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Test 'internal' subproject
        run: ./gradlew :types-internal:linuxTest
      - name: Test root project
        run: ./gradlew :linuxTest
  macos-test:
    name: Kotlin Native tests for macOS
    needs: gradle-checks
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Test 'internal' subproject on macOS x64
        run: ./gradlew :types-internal:macosTest
      - name: Test 'internal' subproject on macOS arm64
        run: ./gradlew :types-internal:macosArm64Test
      - name: Test root project on macOS x64
        run: ./gradlew :macosTest
      - name: Test root project on macOS arm64
        run: ./gradlew :macosArm64Test
  windows-test:
    name: Kotlin Native tests for Windows
    needs: gradle-checks
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Test 'internal' subproject
        run: ./gradlew :types-internal:windowsTest
      - name: Test root project
        run: ./gradlew :windowsTest
  # --------------------------------- Stage 3 ----------------------------------
  dependency-submission:
    name: Dependency submission
    needs:
      - js-test
      - jvm-checks
      - linux-test
      - macos-test
      - windows-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3.1.0
