name: Integration
on:
  push:
    branches: [ main ]
    paths: [ '*.kts', '*gradle*', .github/workflows/delivery.yml, src/** ]
jobs:
  # ---------- Stage 1 ----------
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
  # ---------- Stage 2 ----------
  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    needs: validate-wrapper
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the application
        run: ./gradlew build --no-daemon
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    needs: validate-wrapper
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the application
        run: ./gradlew build --no-daemon
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    needs: validate-wrapper
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the application
        run: ./gradlew build --no-daemon
