name: Types Integration & Delivery
on:
  push:
    branches: [ main ]
    paths:
      - './*gradle*'
      - .github/workflows/types-integration-delivery.yml
      - buildSrc/**/*.kt*
      - types/**/*.kt*
  workflow_dispatch:
permissions: read-all
env:
  CACHING: gradle
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_USER: ${{ secrets.GIT_USER }}
  GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  JAVA_DISTRIBUTION: adopt
  JAVA_VERSION: 8
  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
jobs:
  # ---------- Stage 1 ----------
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.5
  # ---------- Stage 2 ----------
  test-deliver-js:
    name: Test & deliver JS package
    needs: validate-wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.6.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Run tests
        run: ./gradlew types:jsTest --no-daemon
      - name: Deliver package
        run: ./gradlew types:publishJsPublicationToOSSRHRepository --no-daemon
  test-deliver-jvm:
    name: Test & deliver JVM package
    needs: validate-wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.6.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Run tests
        run: ./gradlew types:jvmTest --no-daemon
      - name: Deliver package
        run: ./gradlew types:publishJvmPublicationToOSSRHRepository --no-daemon
  test-deliver-linux:
    name: Test & deliver Linux package
    needs: validate-wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.6.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Run tests
        run: ./gradlew types:linuxX64Test --no-daemon
      - name: Deliver package
        run: ./gradlew types:publishLinuxX64PublicationToOSSRHRepository --no-daemon
  test-deliver-macos:
    name: Test & deliver macOS package
    needs: validate-wrapper
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.6.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Run tests
        run: ./gradlew types:macosX64Test --no-daemon
      - name: Deliver package
        run: ./gradlew types:publishMacosX64PublicationToOSSRHRepository --no-daemon
  test-deliver-windows:
    name: Test & deliver Windows package
    needs: validate-wrapper
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.6.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Run tests
        run: ./gradlew types:mingwX64Test --no-daemon
      - name: Deliver package
        run: ./gradlew types:publishMingwX64PublicationToOSSRHRepository --no-daemon
  # ---------- Stage 3 ----------
  deliver-multiplatform:
    name: Deliver multiplatform package
    needs:
      - test-deliver-js
      - test-deliver-jvm
      - test-deliver-linux
      - test-deliver-macos
      - test-deliver-windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.6.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Deliver package
        run: ./gradlew types:publishKotlinMultiplatformPublicationToOSSRHRepository --no-daemon
